### PR TITLE
Added live discover.

### PR DESCRIPTION
**Pull request by Chris-Smith-Dentons**
New-UriWithQuery handles array parameters

### CODE REVIEW

**Comment by simon-r-watson** [comment]
Looks good, thanks for your work on this!

I'll merge it, I've done some initial testing of the changes to New-UriWithQuery. I won't be able to test the LiveDiscover for a little while, but it looks good.

**Comment by Chris-Smith-Dentons** [comment]
Looks good – have been doing some testing today.

A couple of things (btw – let me know if you want to me raise these as issue or just discuss by email).

In Get-SophosCentralLiveDiscoverQueryRun I am filtering out some parameters to stop them ending up in the URI

    $filteredPsBoundParameters = $PsBoundParameters
    #filter out parameters not needed for Query
    $null = ('Results', 'Endpoints', 'RunID') | ForEach-Object { $filteredPsBoundParameters.Remove($_) }
    $uri = New-UriWithQuery -Uri $uriTemp -OriginalPsBoundParameters $filteredPsBoundParameters

Maybe this could go in New-UriWithQuery so we can pass in parameters we know need filtering – something like

$uri = New-UriWithQuery -Uri $uriTemp -OriginalPsBoundParameters $filteredPsBoundParameters –parmetersToFilter ('Results', 'Endpoints', 'RunID')

There are some other commands that are adding extra queries into the URI (e.g. Get-SophosCentraXDRQueryRun)  – could fix them up in this way

Also your implementation of Invoke-SophosCentralXDRQuery has a parameter of –customBody  - for Invoke-SophosCentralLiveDiscoverQuery I changed this to –query – we should standardise on one or the other – let me know what you think

I can make these changes in a branch and submit another pull if you want.

Thanks

Chris

**Comment by simon-r-watson** [comment]
Yes, I think we should update 'New-UriWithQuery'. There's probably also other items that need filtering from it as well (such as ErrorAction, etc)

I was testing having Invoke-RestMethod (by using a get request with a hashtable as the body) handle generating URI with the query parameters itself instead of using 'New-UriWithQuery', however that doesn't handle arrays based on the my initial testing using 'Get-SophosCentralUser' with SearchFields as an array.  So we'd probably need to keep using 'New-UriWithQuery'.

For 'Invoke-SophosCentralXDRQuery', my thought process was to at a later date update that with additional parameters, so people would be able to use the parameters to generate the query we post to the API, whilst still allowing the option to provide a custom query body if required.

So the options would be something like:

Custom

```
$body = @{'whatever they want as a custom query'}
Invoke-SophosCentralXDRQuery' -CustomBody $body
```

Adhoc

```
$from = (Get-Date).AddDays(-7)
$to = Get-Date
$endpoints = Get-SophosCentralEndpoint -HealthStatus 'bad'
Invoke-SophosCentralXDRQueryRun -Template 'select * from "xdr_data" limit 10' -Name 'test-search' -From $from -To $to -EndpointID ($endpoints).id
```

Saved Query

```
Invoke-SophosCentralXDRQueryRun -SavedQueryId '4c966626-8dac-47a5-920e-2a31c7eeacba'
```


I don't have an XDR tenant I can test with at the moment, so haven't started looking at implementing those parameters yet

**Comment by Chris-Smith-Dentons** [comment]
Agree on that – will do the code for the parameter filtering and have a look at the invoke-soposcentral*query.


Chris

**Comment by Chris-Smith-Dentons** [comment]
Submitted pull request with these changes.

I am having issues with multiple filters in queries:

PS C:\Users\dubadmin> Invoke-SophosCentralLiveDiscoverQueryRun -query "select * from file WHERE path = 'c:\windows\system32\drivers\etc\hosts'" -ipAddresses ("10.164.5.150") -hostnameContains "17"|select endpointcounts

endpointCounts
--------------
@{total=4; types=; platforms=; statuses=}

PS C:\Users\dubadmin> Invoke-SophosCentralLiveDiscoverQueryRun -query "select * from file WHERE path = 'c:\windows\system32\drivers\etc\hosts'" -ipAddresses ("10.164.5.150") |select endpointcounts

endpointCounts
--------------
@{total=1; types=; platforms=; statuses=}

PS C:\Users\dubadmin>

It look like multiple filter are an OR not an AND? Have you noticed this – had a good look at the body json and looked OK.

Chris

**Pull request merged**
