### PR TITLE
Added -filteredParmeters to function New-UriWithQuery, updated Invoke…

### PR DESCRIPTION
**Pull request by Chris-Smith-Dentons**
…-SophosCentralLiveDiscoverQueryRun with full api parameter set

### CODE REVIEW

**Comment by Chris-Smith-Dentons** [comment]
Added -filteredParmeters to function New-UriWithQuery, SophosCentralLiveDiscoverQueryRun with full api parameter set

**Comment by simon-r-watson** [comment]
Looks good, thanks!

**Comment by Chris-Smith-Dentons** [comment]
Hey Simon,

Have tidied up the way it builds the data structures for the live discovery queries and made the invoke-sophoscentralXDRqueryrun fully functional. Still some work to do so have not submitted pull yet but just letting you know in case you were going to work on them.

Thanks

Chris

**Comment by Chris-Smith-Dentons** [comment]
Sill testing XDR and live queries – have an issue which may be an API problem – when I submit multiple filters it only seems to be honouring one of them. I only have 4 endpoints that match “17”:

[DBG]: PS C:\Users\dubadmin> invoke-SophosCentralLiveDiscoverQueryRun -Query "select * from curl where url='http://icanhazip.com'"  -hostnameContains "17" -verbose
Custom Query
{
  "matchEndpoints": {
    "filters": [
      {
        "hostnameContains": "17"
      }
    ]
  },
  "adHocQuery": {
    "name": "AdHoc",
    "template": "select * from curl where url='http://icanhazip.com'"
  }
}
https://api-eu01.central.sophos.com/live-discover/v1/queries/runs
POST with 227-byte payload
received -byte response of content type application/json
Content encoding: utf-8

id                     : 0da6c50f-2633-48be-bd56-f2ab94bfcc91
name                   : AdHoc
template               : select * from curl where url='http://icanhazip.com'
variables              : {}
status                 : started
result                 : notAvailable
createdAt              : 11/17/2022 3:47:32 AM
createdBy              : @{id=30f057cf-c52d-4c66-b761-a14c9fc8c646; type=service; accountType=organization}
maxDurationInSeconds   : 600
timeRemainingInSeconds : 600
performance            : @{score=notEvaluated; dataTransferredInBytes=; executionTimeInMillis=}
endpointIds            : {1819be89-5de2-4a63-97ef-dd19aeb3da9f, 853f6ec3-fa4d-4e69-8c64-e2328ff37b82, da8284c5-1b38-4085-9498-677d94e66a9c, e7c393d2-d5b1-4b67-9577-b7ca65801d3e}
matchEndpoints         : @{all=False; filters=System.Object[]}
endpointCounts         : @{total=4; types=; platforms=; statuses=}


[DBG]: PS C:\Users\dubadmin> invoke-SophosCentralLiveDiscoverQueryRun -Query "select * from curl where url='http://icanhazip.com'"  -hostnameContains "17" -lastSeenAfter (Get-Date).AddSeconds(-120) -verbose
Custom Query
{
  "matchEndpoints": {
    "filters": [
      {
        "lastSeenAfter": "2022-11-17t03:46:54Z"
      },
      {
        "hostnameContains": "17"
      }
    ]
  },
  "adHocQuery": {
    "name": "AdHoc",
    "template": "select * from curl where url='http://icanhazip.com'"
  }
}
https://api-eu01.central.sophos.com/live-discover/v1/queries/runs
POST with 295-byte payload
received -byte response of content type application/json
Content encoding: utf-8

id                     : 004204e5-7bfe-4f4d-bfba-b340cce02668
name                   : AdHoc
template               : select * from curl where url='http://icanhazip.com'
variables              : {}
status                 : started
result                 : notAvailable
createdAt              : 11/17/2022 3:48:55 AM
createdBy              : @{id=30f057cf-c52d-4c66-b761-a14c9fc8c646; type=service; accountType=organization}
maxDurationInSeconds   : 600
timeRemainingInSeconds : 600
performance            : @{score=notEvaluated; dataTransferredInBytes=; executionTimeInMillis=}
endpointIds            : {1ad4cb11-55ed-43bd-8738-2a8b1f89380f, 34579682-ef41-4f2b-a6a8-606e1798c3bc, 978c4c50-4463-4399-a475-dc9324fd724e, 1819be89-5de2-4a63-97ef-dd19aeb3da9f…}
matchEndpoints         : @{all=False; filters=System.Object[]}
endpointCounts         : @{total=7; types=; platforms=; statuses=}


[DBG]: PS C:\Users\dubadmin>



JSON looks OK.

Have you seen this – can you test in your environment.


Thanks

Chris


From: Smith, Chris
Sent: Monday, 14 November 2022 4:23 PM
To: 'simon-r-watson/SophosCentral' ***@***.***>; simon-r-watson/SophosCentral ***@***.***>
Cc: State change ***@***.***>
Subject: RE: [simon-r-watson/SophosCentral] Added -filteredParmeters to function New-UriWithQuery, updated Invoke… (PR #10)

Hey Simon,

Have tidied up the way it builds the data structures for the live discovery queries and made the invoke-sophoscentralXDRqueryrun fully functional. Still some work to do so have not submitted pull yet but just letting you know in case you were going to work on them.

Thanks

Chris

**Comment by Chris-Smith-Dentons** [comment]
Ignore that – the json should look like this, both seem to be valid but this is “and” and the other is “or”:

{
  "matchEndpoints": {
    "filters": [
      {
        "hostnameContains": "17",
        "lastSeenAfter": "2022-11-17t05:23:10Z"
      }
    ]
  },
  "adHocQuery": {
    "template": "select * from curl where url='http://icanhazip.com'",
    "name": "AdHoc"
  }
}

If that makes sense!

Will modify the code to fix.

Chris


From: Smith, Chris
Sent: Thursday, 17 November 2022 2:51 PM
To: 'simon-r-watson/SophosCentral' ***@***.***>; 'simon-r-watson/SophosCentral' ***@***.***>
Cc: 'State change' ***@***.***>
Subject: RE: [simon-r-watson/SophosCentral] Added -filteredParmeters to function New-UriWithQuery, updated Invoke… (PR #10)

Sill testing XDR and live queries – have an issue which may be an API problem – when I submit multiple filters it only seems to be honouring one of them. I only have 4 endpoints that match “17”:

[DBG]: PS C:\Users\dubadmin> invoke-SophosCentralLiveDiscoverQueryRun -Query "select * from curl where url='http://icanhazip.com'"  -hostnameContains "17" -verbose
Custom Query
{
  "matchEndpoints": {
    "filters": [
      {
        "hostnameContains": "17"
      }
    ]
  },
  "adHocQuery": {
    "name": "AdHoc",
    "template": "select * from curl where url='http://icanhazip.com'"
  }
}
https://api-eu01.central.sophos.com/live-discover/v1/queries/runs
POST with 227-byte payload
received -byte response of content type application/json
Content encoding: utf-8

id                     : 0da6c50f-2633-48be-bd56-f2ab94bfcc91
name                   : AdHoc
template               : select * from curl where url='http://icanhazip.com'
variables              : {}
status                 : started
result                 : notAvailable
createdAt              : 11/17/2022 3:47:32 AM
createdBy              : @{id=30f057cf-c52d-4c66-b761-a14c9fc8c646; type=service; accountType=organization}
maxDurationInSeconds   : 600
timeRemainingInSeconds : 600
performance            : @{score=notEvaluated; dataTransferredInBytes=; executionTimeInMillis=}
endpointIds            : {1819be89-5de2-4a63-97ef-dd19aeb3da9f, 853f6ec3-fa4d-4e69-8c64-e2328ff37b82, da8284c5-1b38-4085-9498-677d94e66a9c, e7c393d2-d5b1-4b67-9577-b7ca65801d3e}
matchEndpoints         : @{all=False; filters=System.Object[]}
endpointCounts         : @{total=4; types=; platforms=; statuses=}


[DBG]: PS C:\Users\dubadmin> invoke-SophosCentralLiveDiscoverQueryRun -Query "select * from curl where url='http://icanhazip.com'"  -hostnameContains "17" -lastSeenAfter (Get-Date).AddSeconds(-120) -verbose
Custom Query
{
  "matchEndpoints": {
    "filters": [
      {
        "lastSeenAfter": "2022-11-17t03:46:54Z"
      },
      {
        "hostnameContains": "17"
      }
    ]
  },
  "adHocQuery": {
    "name": "AdHoc",
    "template": "select * from curl where url='http://icanhazip.com'"
  }
}
https://api-eu01.central.sophos.com/live-discover/v1/queries/runs
POST with 295-byte payload
received -byte response of content type application/json
Content encoding: utf-8

id                     : 004204e5-7bfe-4f4d-bfba-b340cce02668
name                   : AdHoc
template               : select * from curl where url='http://icanhazip.com'
variables              : {}
status                 : started
result                 : notAvailable
createdAt              : 11/17/2022 3:48:55 AM
createdBy              : @{id=30f057cf-c52d-4c66-b761-a14c9fc8c646; type=service; accountType=organization}
maxDurationInSeconds   : 600
timeRemainingInSeconds : 600
performance            : @{score=notEvaluated; dataTransferredInBytes=; executionTimeInMillis=}
endpointIds            : {1ad4cb11-55ed-43bd-8738-2a8b1f89380f, 34579682-ef41-4f2b-a6a8-606e1798c3bc, 978c4c50-4463-4399-a475-dc9324fd724e, 1819be89-5de2-4a63-97ef-dd19aeb3da9f…}
matchEndpoints         : @{all=False; filters=System.Object[]}
endpointCounts         : @{total=7; types=; platforms=; statuses=}


[DBG]: PS C:\Users\dubadmin>



JSON looks OK.

Have you seen this – can you test in your environment.


Thanks

Chris


From: Smith, Chris
Sent: Monday, 14 November 2022 4:23 PM
To: 'simon-r-watson/SophosCentral' ***@***.******@***.***>>; simon-r-watson/SophosCentral ***@***.******@***.***>>
Cc: State change ***@***.******@***.***>>
Subject: RE: [simon-r-watson/SophosCentral] Added -filteredParmeters to function New-UriWithQuery, updated Invoke… (PR #10)

Hey Simon,

Have tidied up the way it builds the data structures for the live discovery queries and made the invoke-sophoscentralXDRqueryrun fully functional. Still some work to do so have not submitted pull yet but just letting you know in case you were going to work on them.

Thanks

Chris

**Pull request merged**
